<%@page import="java.util.List,model.*"%><%@page contentType="text/html" pageEncoding="UTF-8"%>
<% LearningMaterial m=(LearningMaterial)request.getAttribute("material"); List<VideoCheckpoint> cps=(List<VideoCheckpoint>)request.getAttribute("checkpoints"); %>
<jsp:include page="/views/common/header.jsp"/><jsp:include page="/views/common/sidebar.jsp"/>
<main class="main-content"><div class="content-body materials-page"><section class="viewer-header"><div><a class="back-link" href="<%=request.getContextPath()%>/materials">← Kho học liệu</a><span class="eyebrow"><%=m.getMaterialType()%></span><h1><%=m.getTitle()%></h1><p><%=m.getDescription()==null?"":m.getDescription()%></p></div><a class="btn" href="<%=request.getContextPath()%>/materials?action=download&id=<%=m.getMaterialId()%>">Tải xuống</a></section><section class="material-viewer">
<% if("VIDEO".equals(m.getMaterialType())&&m.getYoutubeEmbedId()!=null){ %><div id="youtubePlayer" class="video-wrap"></div><script src="https://www.youtube.com/iframe_api"></script>
<% } else if("VIDEO".equals(m.getMaterialType())&&m.getVideoUrl()!=null){ %><video id="learningVideo" controls class="learning-video"><source src="<%=m.getVideoUrl()%>"></video>
<% } else if("PDF".equals(m.getMaterialType())) { %><iframe class="document-frame" title="<%=m.getTitle()%>" src="<%=request.getContextPath()%>/materials?action=preview&id=<%=m.getMaterialId()%>"></iframe>
<% } else if(m.getVideoUrl()!=null&&!m.getVideoUrl().trim().isEmpty()) { %><iframe class="document-frame" title="<%=m.getTitle()%>" src="<%=m.getVideoUrl()%>"></iframe>
<% } else { %><div class="viewer-empty"><div>▧</div><h2>Bản trình chiếu chưa có liên kết xem trực tuyến</h2><p>Thêm liên kết công khai Google Slides hoặc Office Online ở trường “Liên kết video/URL” để trình chiếu trực tiếp trên web.</p><a class="btn btn-primary" href="<%=request.getContextPath()%>/materials?action=edit&id=<%=m.getMaterialId()%>">Cập nhật liên kết</a></div><% } %>
</section></div></main>
<div id="questionModal" class="checkpoint-modal"><div class="checkpoint-box"><h3>Kiểm tra kiến thức</h3><p id="questionText"></p><div id="options"></div><p id="feedback"></p><button id="submitAnswer" class="btn btn-primary">Gửi câu trả lời</button></div></div>
<script>const checkpoints=[<%for(int i=0;i<cps.size();i++){VideoCheckpoint c=cps.get(i);if(i>0)out.print(",");%>{id:<%=c.getCheckpointId()%>,seconds:<%=c.getStopTimeSeconds()%>,question:<%=json(c.getQuestionPrompt())%>,options:[<%=json(c.getOptionA())%>,<%=json(c.getOptionB())%>,<%=json(c.getOptionC())%>,<%=json(c.getOptionD())%>]}<%}%>];let answered=new Set(),active=null,video,yt;const modal=document.getElementById('questionModal');function show(cp){active=cp;modal.style.display='flex';questionText.textContent=cp.question;feedback.textContent='';options.innerHTML=cp.options.map((x,i)=>x?'<label class="answer-option"><input type="radio" name="answer" value="'+i+'"> '+x+'</label>':'').join('');}function tick(t){if(!active)checkpoints.forEach(c=>{if(!answered.has(c.id)&&t>=c.seconds&&t<c.seconds+1){if(video)video.pause();if(yt)yt.pauseVideo();show(c);}})}submitAnswer.onclick=async()=>{let r=document.querySelector('input[name=answer]:checked');if(!r)return;let data=await fetch('<%=request.getContextPath()%>/materials',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'answerCheckpoint',checkpointId:active.id,selectedOption:r.value})}).then(x=>x.json());if(data.correct){answered.add(active.id);modal.style.display='none';active=null;if(video)video.play();if(yt)yt.playVideo();}else{feedback.textContent='Chưa đúng. '+data.explanation;if(video)video.currentTime=Math.max(0,video.currentTime-15);if(yt)yt.seekTo(Math.max(0,yt.getCurrentTime()-15),true);}};<%if("VIDEO".equals(m.getMaterialType())&&m.getYoutubeEmbedId()!=null){%>function onYouTubeIframeAPIReady(){yt=new YT.Player('youtubePlayer',{videoId:'<%=m.getYoutubeEmbedId()%>',events:{onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING)setInterval(()=>tick(yt.getCurrentTime()),500)}}});}<%}else{%>video=document.getElementById('learningVideo');if(video)video.addEventListener('timeupdate',()=>tick(video.currentTime));<%}%></script>
<%!String json(String s){if(s==null)return "null";return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ")+"\"";}%><jsp:include page="/views/common/footer.jsp"/>
