package controller;
import dal.*; import jakarta.servlet.*; import jakarta.servlet.annotation.MultipartConfig; import jakarta.servlet.http.*; import java.io.*; import java.sql.Date; import java.util.*; import model.*;

@MultipartConfig(maxFileSize=52428800)
public class MaterialServlet extends HttpServlet {
 private final MaterialDAO dao=new MaterialDAO(); private final DepartmentDAO departments=new DepartmentDAO(); private final PositionDAO positions=new PositionDAO(); private final UserDAO users=new UserDAO();
 protected void doGet(HttpServletRequest q,HttpServletResponse s)throws ServletException,IOException{User u=current(q,s);if(u==null)return;String a=param(q,"action","list");
  if("download".equals(a)||"preview".equals(a)){stream(q,s);return;} if("answerCheckpoint".equals(a)){answer(q,s,u);return;}
  if("list".equals(a)){q.setAttribute("materials",dao.getMaterials(u.getUserId()));q.setAttribute("classes",dao.getClasses(u.getUserId(),true));go(q,s,"/views/materials/material-list.jsp");return;}
  if("view".equals(a)){int id=num(q,"id");LearningMaterial m=dao.getMaterial(id);if(m==null){s.sendRedirect(q.getContextPath()+"/materials");return;}q.setAttribute("material",m);q.setAttribute("checkpoints",dao.getCheckpoints(id));go(q,s,"/views/materials/material-detail.jsp");return;}
  if("classList".equals(a)){q.setAttribute("classes",dao.getClasses(u.getUserId(),false));go(q,s,"/views/materials/class-list.jsp");return;}
  if("classDetail".equals(a)){TrainingClass c=dao.getClassById(num(q,"id"));if(c==null){s.sendRedirect(q.getContextPath()+"/materials?action=classList");return;}q.setAttribute("trainingClass",c);go(q,s,"/views/materials/class-detail.jsp");return;}
  if("classAssign".equals(a)){if(!canManage(u)){deny(s,q);return;}int id=num(q,"id");q.setAttribute("trainingClass",dao.getClassById(id));q.setAttribute("candidates",dao.getSmartCandidatesForClass(id));go(q,s,"/views/materials/class-assign.jsp");return;}
  if("create".equals(a)||"edit".equals(a)){if(!canManage(u)){deny(s,q);return;}formData(q);q.setAttribute("material","edit".equals(a)?dao.getMaterial(num(q,"id")):new LearningMaterial());go(q,s,"/views/materials/material-form.jsp");return;}
  if("classCreate".equals(a)){if(!canManage(u)){deny(s,q);return;}formData(q);q.setAttribute("materials",dao.getMaterials(null));go(q,s,"/views/materials/class-form.jsp");return;} s.sendRedirect(q.getContextPath()+"/materials"); }
 protected void doPost(HttpServletRequest q,HttpServletResponse s)throws ServletException,IOException{User u=current(q,s);if(u==null)return;String a=param(q,"action","");if(!"answerCheckpoint".equals(a)&&!canManage(u)){deny(s,q);return;}
  if("saveMaterial".equals(a)){LearningMaterial m=material(q,u);boolean ok=m.getMaterialId()>0?dao.updateMaterial(m):dao.saveMaterial(m);flash(q,ok?"Lưu học liệu thành công.":"Không thể lưu học liệu.");s.sendRedirect(q.getContextPath()+"/materials");return;}
  if("deleteMaterial".equals(a)){dao.deleteMaterial(num(q,"id"));flash(q,"Đã xóa học liệu.");s.sendRedirect(q.getContextPath()+"/materials");return;}
  if("saveClass".equals(a)){TrainingClass c=new TrainingClass();c.setClassCode(q.getParameter("classCode"));c.setClassName(q.getParameter("className"));c.setDescription(q.getParameter("description"));c.setDepartmentId(opt(q,"departmentId"));c.setTargetPositionId(opt(q,"positionId"));c.setTargetLevelId(opt(q,"levelId"));c.setMentorId(opt(q,"mentorId"));c.setStartDate(Date.valueOf(q.getParameter("startDate")));String end=q.getParameter("endDate");if(end!=null&&!end.isEmpty())c.setEndDate(Date.valueOf(end));c.setStatus(param(q,"status","OPEN"));c.setCreatedBy(u.getUserId());String[] selected=q.getParameterValues("materialIds");int[] ids=selected==null?null:Arrays.stream(selected).mapToInt(Integer::parseInt).toArray();int id=dao.saveClass(c,ids);flash(q,id>0?"Mở lớp đào tạo thành công.":"Không thể mở lớp.");s.sendRedirect(q.getContextPath()+"/materials?action=classList");return;}
  if("enrollSubmit".equals(a)){int n=dao.enrollBatch(num(q,"classId"),q.getParameterValues("userIds"),u.getUserId());flash(q,"Đã ghi danh "+n+" nhân sự.");s.sendRedirect(q.getContextPath()+"/materials?action=classAssign&id="+num(q,"classId"));return;}
  if("addCheckpoint".equals(a)){VideoCheckpoint x=new VideoCheckpoint();x.setMaterialId(num(q,"materialId"));x.setStopTimeSeconds(num(q,"stopTimeSeconds"));x.setQuestionPrompt(q.getParameter("questionPrompt"));x.setOptionA(q.getParameter("optionA"));x.setOptionB(q.getParameter("optionB"));x.setOptionC(q.getParameter("optionC"));x.setOptionD(q.getParameter("optionD"));x.setCorrectOption(num(q,"correctOption"));x.setExplanation(q.getParameter("explanation"));dao.addCheckpoint(x);s.sendRedirect(q.getContextPath()+"/materials?action=edit&id="+x.getMaterialId());return;}
  if("answerCheckpoint".equals(a))answer(q,s,u);else s.sendRedirect(q.getContextPath()+"/materials"); }
 private void answer(HttpServletRequest q,HttpServletResponse s,User u)throws IOException{int cp=num(q,"checkpointId"),selected=num(q,"selectedOption");VideoCheckpoint x=dao.getCheckpoint(cp);boolean correct=x!=null&&x.getCorrectOption()==selected;dao.recordAnswer(cp,u.getUserId(),selected);s.setContentType("application/json;charset=UTF-8");s.getWriter().print("{\"ok\":true,\"correct\":"+correct+",\"explanation\":\""+json(x==null?"":x.getExplanation())+"\"}");}
 private void stream(HttpServletRequest q,HttpServletResponse s)throws IOException{LearningMaterial m=dao.getMaterial(num(q,"id"));if(m==null){s.sendError(404);return;}byte[] data=dao.getMaterialFile(m.getMaterialId());if(data==null){s.sendError(404,"Tệp chưa được tải lên; hãy dùng liên kết xem trực tuyến nếu có.");return;}s.setContentType(m.getFileType()==null?"application/octet-stream":m.getFileType());String disposition="preview".equals(q.getParameter("action"))?"inline":"attachment";s.setHeader("Content-Disposition",disposition+"; filename=\""+(m.getFileName()==null?"material":m.getFileName().replace("\"",""))+"\"");s.setContentLength(data.length);s.getOutputStream().write(data);}
 private LearningMaterial material(HttpServletRequest q,User u){LearningMaterial m=new LearningMaterial();m.setMaterialId(num(q,"id"));m.setTitle(q.getParameter("title"));m.setDescription(q.getParameter("description"));m.setMaterialType(q.getParameter("materialType"));m.setScopeType(q.getParameter("scopeType"));m.setDepartmentId("DEPARTMENT".equals(m.getScopeType())?opt(q,"departmentId"):null);m.setPositionId(opt(q,"positionId"));m.setLevelId(opt(q,"levelId"));m.setFileName(q.getParameter("fileName"));m.setFileType(q.getParameter("fileType"));try{Part file=q.getPart("materialFile");if(file!=null&&file.getSize()>0){m.setFileName(file.getSubmittedFileName());m.setFileType(file.getContentType());m.setFileData(file.getInputStream().readAllBytes());}}catch(Exception ignored){}m.setVideoUrl(q.getParameter("videoUrl"));m.setDurationMinutes(num(q,"durationMinutes"));m.setStatus(q.getParameter("status")!=null);m.setCreatedBy(u.getUserId());return m;}
 private void formData(HttpServletRequest q){q.setAttribute("departments",departments.getAllDepartments());q.setAttribute("positions",positions.getAllPositions());q.setAttribute("levels",positions.getAllJobLevels());q.setAttribute("mentors",users.getManagersCandidates());}
 private User current(HttpServletRequest q,HttpServletResponse s)throws IOException{HttpSession h=q.getSession(false);if(h==null||h.getAttribute("currentUser")==null){s.sendRedirect(q.getContextPath()+"/login");return null;}return(User)h.getAttribute("currentUser");} private boolean canManage(User u){return u.getRoleId()<=3;} private void deny(HttpServletResponse s,HttpServletRequest q)throws IOException{s.sendRedirect(q.getContextPath()+"/materials");} private int num(HttpServletRequest q,String n){try{return Integer.parseInt(q.getParameter(n));}catch(Exception e){return 0;}} private Integer opt(HttpServletRequest q,String n){int x=num(q,n);return x>0?x:null;} private String param(HttpServletRequest q,String n,String d){String v=q.getParameter(n);return v==null||v.trim().isEmpty()?d:v;} private void go(HttpServletRequest q,HttpServletResponse s,String p)throws ServletException,IOException{q.getRequestDispatcher(p).forward(q,s);} private void flash(HttpServletRequest q,String v){q.getSession().setAttribute("successMessage",v);} private String json(String x){return x==null?"":x.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ");}
}
